output SPN_Client_ID {
  value       = azuread_application.appReg.application_id
  description = "The Application ID (also called Client ID)."
}


output SPN_Client_Secret {
  value       = azuread_application_password.appReg_secret.value
  description = "The password for this application, which is generated by Azure Active Directory (also called Client secret)."
  sensitive   = true
}