# Re-usable stage template to deploy terraform Infrastructure on dv environments

parameters:
  dependsOnEnvironment: ''
  environmentName: ''
  environmentServiceName: ''
  projectName: ''
  remoteStateContainerName: ''
  remoteStateResourceGroup: ''
  remoteStateServiceConnection: ''
  remoteStateStorageName: ''
  terraformCommandOptions: ''
  terraformWorkingDirectory: ''

stages:
  - stage: deploy_${{ parameters.environmentName }}_infrastructure
    dependsOn: 
      - Validate_infrastructure
      - ${{ if ne(parameters.dependsOnEnvironment, '' ) }}:
        - deploy_${{ parameters.dependsOnEnvironment }}_infrastructure
    displayName: 'Deploy ${{ parameters.environmentName }} infrastructure'
    jobs:            
      - template: /.azdo/jobs/approvals.yaml
        parameters: 
          environmentName: '${{ parameters.environmentName }}'
          projectName: '${{ parameters.projectName }}'

      - template: /.azdo/jobs/deploy-Infrastructure.yaml
        parameters: 
          environmentServiceName: '${{ parameters.environmentServiceName }}'
          remoteStateContainerName: '${{ parameters.remoteStateContainerName }}'
          remoteStateFileName: '${{ parameters.environmentName }}.tfstate' 
          remoteStateResourceGroup: '${{ parameters.remoteStateResourceGroup }}'
          remoteStateServiceConnection: '${{ parameters.remoteStateServiceConnection }}'
          remoteStateStorageName: '${{ parameters.remoteStateStorageName }}'
          terraformWorkingDirectory: '${{ parameters.terraformWorkingDirectory }}'
          terraformCommandOptions: '${{ parameters.terraformCommandOptions }}'