# calling this deployment job at the beginning of a stage will allow approvals checks for the stage

parameters:
  environmentName: ''
  projectName: ''

jobs:
  - deployment: pending_approval
    displayName: 'Pending Approval'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'terraform_${{ parameters.projectName }}_${{ parameters.environmentName }}'
    strategy: 
      runOnce:
        deploy:
          steps:
            - script: 'echo approved'
              displayName: "Waiting on approval"