parameters:
  environmentServiceName: ''
  remoteStateContainerName: ''
  remoteStateFileName: ''
  remoteStateResourceGroup: ''
  remoteStateServiceConnection: ''
  remoteStateStorageName: ''
  terraformCommandOptions: ''
  terraformWorkingDirectory: ''

jobs:
  - job: deploy_infrastructure
    timeoutInMinutes: 0
    displayName: 'Deploy Terraform Infrastructure'
    pool:
      name: 'terraform'
    steps: 
      - template: /.azdo/steps/deploy-terraform-dv.yaml
        parameters:
          environmentServiceName: '${{ parameters.environmentServiceName }}'
          remoteStateContainerName: '${{ parameters.remoteStateContainerName }}'
          remoteStateFileName: '${{ parameters.remoteStateFileName }}'
          remoteStateResourceGroup: '${{ parameters.remoteStateResourceGroup }}'
          remoteStateServiceConnection: '${{ parameters.remoteStateServiceConnection }}'
          remoteStateStorageName: '${{ parameters.remoteStateStorageName }}'
          terraformCommandOptions: '${{ parameters.terraformCommandOptions }}'
          workingDirectory: '${{ parameters.terraformWorkingDirectory }}'